### PR TITLE
Reverse the order of entity nodes in diagram, but not in variable tree

### LINKED ISSUE #859: Bug: Community Repeated measures should come directly after Community
The order of entities in the variable tree for WASHb BNG is incorrect. It should always be in this order:

- Community
- Community Repeated Measures
- Household
- Household Repeated Measures
- Participants
- Participant Repeated Measures
- Samples

image

### PR DESCRIPTION
**Pull request by dmfalke**
The ordering of nodes has been stabilized on the backend, when constructing the entity tree. This requires an adjustment to how the tree is traversed when displaying the variable tree and the entity diagram.

fixes #859

### CODE REVIEW

File: src/lib/core/components/EntityDiagram.tsx [hunk 1]
```diff
@@ -22,6 +25,16 @@ interface Props {
...
+  const entityTree = useMemo((): StudyEntity => {
+    return mapStructure(
+      (node, children) => ({
+        ...node,
+        children: children.slice().reverse(),
+      }),
+      (entity) => entity.children ?? [],
+      studyMetadata.rootEntity
+    );
+  }, []);
```
Comment (jtlong3rd) [inline src/lib/core/components/EntityDiagram.tsx:37]: Missing `studyMetadata` dependency?

**Review by jtlong3rd — COMMENTED** [review]
Aside from one inline suggestion, should be good to merge!

File: src/lib/core/components/EntityDiagram.tsx (hunk 1 above)
Comment (dmfalke) [reply src/lib/core/components/EntityDiagram.tsx:37]: Thank you, yes!
