### PR TITLE
Fix/402/max num values var constraint

### LINKED ISSUE #402: Constrain variables based on `maxValues`
The backend provides this property, but the frontend is not utilizing it.

This is needed to prevent variables with > 8 values from being used as overlay variables, and other similar cases.

### PR DESCRIPTION
**Pull request by d-callan**
should resolve #402, and is related to #310

this appears to be minimally functional to me, though there may be better ways to do things, or silly mistakes ive made. i want all of those thoughts. 

also @dmfalke had a comment in a side conversation earlier that we likely want to apply the constraints to only the Variables rather than the whole tree (including categories/ VariableTreeNodes).

### CODE REVIEW

**Comment by d-callan** [comment]
having got this working locally in combination w veupathdb/edadataservice#88 ive now realized theres some work to do in plot.data for this as well. i mean to do that first, then return to potentially change VariableTreeNode -> Variable. Im off next week though, so if this is needed before that, please feel free.

File: src/lib/core/types/study.ts [hunk 1]
```diff
@@ -57,13 +57,13 @@ export const VariableTreeNode_Base = t.intersection([
...
     displayType: VariableDisplayType,
     dataShape: VariableDataShape,
+    distinctValuesCount: t.number,
   }),
 ]);
 
 const Variable_Base = t.intersection([
   VariableTreeNode_Base,
   t.type({
-    distinctValuesCount: t.number,
```
Comment (dmfalke) [inline src/lib/core/types/study.ts:66]: I don't think this is necessary. When you are using this property in `src/lib/core/utils/data-element-constraints.ts`, the type has been narrowed to a non-category variable, due to the prior `variable.type === 'category'` condition. That condition also means that you don't need to change the signature of the function.

File: src/lib/core/utils/data-element-constraints.ts [hunk 2]
```diff
@@ -62,6 +63,7 @@ export function excludedVariables(
  */
 function variableConstraintPredicate(
   constraint: DataElementConstraint,
+  //maybe this should be variable: Variable - from dave
```
Comment (dmfalke) [inline src/lib/core/utils/data-element-constraints.ts:66]: We don't need to do this, since we are testing against variables that have `type = 'category'`. See comment above.

File: src/lib/core/utils/data-element-constraints.ts [hunk 3]
```diff
@@ -71,6 +73,10 @@ function variableConstraintPredicate(
       constraint.allowedShapes.includes(variable.dataShape)) &&
       (constraint.allowedTypes == null ||
         constraint.allowedTypes.includes(variable.type)) &&
+      (constraint.maxNumValues == null ||
+        //this case should be category anyway, but is that a strong enough thing to assume here?
+        variable.distinctValuesCount === undefined ||
```
Comment (dmfalke) [inline src/lib/core/utils/data-element-constraints.ts:78]: This can also be removed, due to the type narrowing, if the changes in `src/lib/core/types/study.ts` are undone.

File: src/lib/core/utils/data-element-constraints.ts [hunk 4]
```diff
@@ -133,9 +140,18 @@ export function flattenConstraints(
       const shapeIsValid =
         isEmpty(constraint.allowedShapes) ||
         constraint.allowedShapes?.includes(variable.dataShape!);
+      const passesMaxValuesConstraint =
+        constraint.maxNumValues === undefined ||
+        variable.distinctValuesCount === undefined ||
```
Comment (dmfalke) [inline src/lib/core/utils/data-element-constraints.ts:145]: This can also be removed, due to the type narrowing, if the changes in `src/lib/core/types/study.ts` are undone.

**Review by dmfalke — CHANGES_REQUESTED** [review]
This looks pretty good! I made some suggestions to simplify some of the logic. Let me know what you think.

File: src/lib/core/types/study.ts (hunk 1 above)
Comment (d-callan) [reply src/lib/core/types/study.ts:66]: i saw `variable.type === 'category'`, and was slightly confused by it tbh. maybe i was interpretting 'variable' overly literally. but i didnt understand how a variable could be of type 'category'. seemed the condition should always be false, if variable were really a variable.
im mostly guessing really, but i suspect `excludedVariables` handles more than variables, and the narrowing of scope is actually doing something there. and that in `flattenVariables` were seeing only variables, and the narrowing of scope isnt necessary.
in any case i suppose you're right, and i did try that first actually. think vscode started giving me red squigglies though, and my ocd wouldnt allow that.

File: src/lib/core/utils/data-element-constraints.ts (hunk 2 above)
Comment (d-callan) [reply src/lib/core/utils/data-element-constraints.ts:66]: is there any reason to prefer one method over the other? I would have guessed, possibly naively, that just explicitly handling only Variables rather than VariableTreeNodes would be preferred to testing for the condition of meeting a category. what if we introduce some new thing, other than categories, than can be members of VariableTreeNode and not Variable?

File: src/lib/core/types/study.ts (hunk 1 above)
Comment (dmfalke) [reply src/lib/core/types/study.ts:66]: There is not a large distinction made between "variables" and "categories" in the front end or back end code. I tried to make a stronger distinction in the front end code with the types `Variable` and `VariableCategory`. As far as seeing errors in VSCode, I played with these changes and didn't get any errors. Maybe there was something else causing it?

File: src/lib/core/utils/data-element-constraints.ts (hunk 2 above)
Comment (dmfalke) [reply src/lib/core/utils/data-element-constraints.ts:66]: They are really equivalent. In both cases, we would have to deal with categories. The way we have it now simplifies the calling code, and gives us an opportunity to apply constraints to categories, if we decide to in the future.

File: src/lib/core/types/study.ts (hunk 1 above)
Comment (d-callan) [reply src/lib/core/types/study.ts:66]: very possible. hopefully ill get to this soon.

**Review by dmfalke — APPROVED** [review]
