### PR TITLE
My analyses: fix search bar when HTML tags are in study name, also solve endless datasets request

### LINKED ISSUE #780: Studies with HTML tags, such as italicised species, are not filtering properly in the "My analyses" list
For example 
Study **SCORE Seasonal Transmission S. haematobium Cluster Randomized Trial**

Make a new analysis - name it or change a filter or something so it saves - then click "My analyses"
image

The list will be empty, but it shouldn't be!

### PR DESCRIPTION
**Pull request by bobular**
Resolves #780 

Also resolves a hitherto unreported bug (endless loop of study list requests)

The only issue with this solution is that if a user starts typing HTML, they find that it is impossible.  Alternatively we can keep the HTML tags in the search box, and add `'displayNameHTML'` to `searchableDatasetColumns`.

### CODE REVIEW

File: src/lib/core/hooks/study.ts [hunk 1]
```diff
@@ -96,10 +96,11 @@ export function useWdkStudyRecord(datasetId: string): HookValue | undefined {
 
 const DEFAULT_STUDY_ATTRIBUTES = ['dataset_id', 'eda_study_id'];
 const DEFAULT_STUDY_TABLES: string[] = [];
+const EMPTY_ARRAY: string[] = [];
 
 export function useWdkStudyRecords(
-  attributes: AnswerJsonFormatConfig['attributes'] = [],
-  tables: AnswerJsonFormatConfig['tables'] = []
+  attributes: AnswerJsonFormatConfig['attributes'] = EMPTY_ARRAY,
+  tables: AnswerJsonFormatConfig['tables'] = EMPTY_ARRAY
```
Comment (jtlong3rd) [inline src/lib/core/hooks/study.ts:103]: Good catch!

File: src/lib/workspace/AllAnalyses.tsx [hunk 2]
```diff
@@ -94,7 +94,8 @@ export function AllAnalyses(props: Props) {
   const classes = useStyles();
 
   const queryParams = new URLSearchParams(location.search);
-  const searchText = queryParams.get('s') ?? '';
+  const searchParam = queryParams.get('s') ?? '';
+  const searchText = stripHTML(searchParam); // matches stripHTML(dataset.displayName) below
```
Comment (jtlong3rd) [inline src/lib/workspace/AllAnalyses.tsx:98]: If we go with this solution over the alternative solution, let's `useMemo`-ize `searchText`.

**Review by jtlong3rd — APPROVED** [review]
I don't have strong feelings about this solution vs. the alternative solution! I suspect that our typical user won't be trying to type HTML into the search bar, so this solution is likely OK.
